---
- name: Install PostgreSQL
  apt:
    name:
    - acl # needed by postgresql_user module (https://github.com/georchestra/ansible/issues/55#issuecomment-588313638)
    - postgresql
    - postgresql-client

- name: Gather package facts
  package_facts:

- name: Extract PostgreSQL major version
  set_fact:
    postgresql_version_major: "{{ ansible_facts.packages['postgresql'][0].version.split('-')[0].split('+')[0] }}"

- name: Create PostgreSQL configuration file
  template:
    src: postgresql.conf.j2
    dest: "/etc/postgresql/{{ postgresql_version_major }}/main/postgresql.conf"
    mode: 0644

- name: Ensure PostgreSQL is started
  service:
    name: postgresql
    state: started

- name: Create cRPG PostgreSQL user
  become_user: postgres
  postgresql_user:
    name: "{{ db_user_crpg }}"
    password: "{{ db_user_crpg_password }}"

# TODO: omit password and use ident authentication (https://github.com/DataDog/integrations-core/pull/7219)
- name: Create Datadog PostgreSQL user
  become_user: postgres
  postgresql_user:
    name: "{{ db_user_datadog }}"
    password: "{{ db_user_datadog_password }}"
    groups: pg_monitor

- name: Create cRPG PostgreSQL database
  become_user: postgres
  postgresql_db:
    name: "{{ db_crpg }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8

- name: Grant Datadog user SELECT permission on crpg
  become_user: postgres
  postgresql_privs:
    database: "{{ db_user_crpg }}"
    privs: SELECT
    objs: ALL_IN_SCHEMA
    role: "{{ db_user_datadog }}"

- name: Restart PostgreSQL
  service:
    name: postgresql
    enabled: yes
    state: restarted
