- hosts: centralservers
  become: yes
  roles:
    - nginx
    - postgresql
    - datadog
    - geoip
    - dotnet
    - crpg-web-api
    - crpg-web-ui
- hosts: gameservers
  become: yes
  roles:
    - datadog
    - crpg-game-server
