- hosts: centralservers
  become: yes
  roles:
    - nginx
    - postgresql
    - datadog
    - geoip
    - dotnet
    - crpg-game-client
    - crpg-web-ui
    - crpg-web-api
# - hosts: gameservers
#   become: yes
#   roles:
#     - datadog
#     - crpg-game-server
